### PR TITLE
gpio: configure(None) correct behavior. Fixes #464

### LINKED ISSUE #464: gpio: configure(None) is a no-op
The GPIO driver is currently implemented such that when you pass `None` to `GPIOPin::configure`, nothing is executed. However, in my opinion, this is incorrect behavior, since passing `None` should instead reset the pin configuration, unassigning it from any currently assigned peripheral.

The problematic code snippet (from [chips/sam4l/src/gpio.rs](chips/sam4l/src/gpio.rs@eb87f17), commit eb87f17):

```rust
impl hil::Controller for GPIOPin {
    type Config = Option<PeripheralFunction>;


    fn configure(&self, config: Option<PeripheralFunction>) {
        config.map(|c| { self.select_peripheral(c); });
    }
}
```

Note that a `None` config causes the method to do nothing.

### PR DESCRIPTION
**Pull request by shaneleonard**
By enabling the GPIO before potentially assigning it to a peripheral, we ensure that calling `configure(None)` will put the pin into GPIO mode, rather than leaving it in the current peripheral mode.

### CODE REVIEW

File: chips/sam4l/src/gpio.rs [hunk 1]
```diff
@@ -448,7 +448,11 @@ impl hil::Controller for GPIOPin {
     type Config = Option<PeripheralFunction>;
 
 
-    fn configure(&self, config: Option<PeripheralFunction>) {
+    fn configure(&self, config: Self::Config) {
+        // Unassign the pin from its current peripheral function.
+        self.enable();
+
+        // If config is Some, select the desired peripheral.
         config.map(|c| { self.select_peripheral(c); });
```
Comment (alevy) [inline chips/sam4l/src/gpio.rs]: maybe better to avoid `enable` if it's unnecessary? So:

```rust
match config {
    Some(c) => self.select_peripheral(c),
    None => self.enable()
}
```

Comment (shaneleonard) [inline chips/sam4l/src/gpio.rs]: My intuition was that calling enable (even unnecessarily) would be faster than branching on every call, but I'm open to change it

Comment (shaneleonard) [inline chips/sam4l/src/gpio.rs]: I guess the map already implicitly branches anyway, so my point is probably moot

Comment (shaneleonard) [inline chips/sam4l/src/gpio.rs]: Is the Self::Config change alright?

File: chips/sam4l/src/gpio.rs [hunk 2]
```diff
@@ -448,7 +448,11 @@ impl hil::Controller for GPIOPin {
     type Config = Option<PeripheralFunction>;
 
 
-    fn configure(&self, config: Option<PeripheralFunction>) {
+    fn configure(&self, config: Self::Config) {
```
Comment (shaneleonard) [inline chips/sam4l/src/gpio.rs]: Changed `Option<PeripheralFunction>` to `Self::Config`, as it seemed to be the intention of the `Config` type

File: chips/sam4l/src/gpio.rs (hunk 1 above)
Comment (alevy) [inline chips/sam4l/src/gpio.rs]: Moreover, inlining is likely to get rid of the branch in both cases, but not of the extraneous enable
