### PR TITLE
Generalize MPU subregions and use where possible

### LINKED ISSUE #382: Possible MPU problem
I'm having a problem running the `userland/examples/tests/adc_continuous` app from #371. Everything was working fine before I rebased on top of master.

If I'm reading the debug report below correctly, it's erroring on address `0x20008E10` which is validly within the Data segment.

```
Kernel panic at /home/brghena/Dropbox/repos/tock/kernel/src/process.rs:295:
    "Process adc_continuous had a fault"
    Kernel version b378e87

---| Fault Status |---
Data Access Violation:              true
Forced Hard Fault:                  true
Faulting Memory Address:            0x20008E10
Fault Status Register (CFSR):       0x00000082
Hard Fault Status Register (HFSR):  0x40000000

---| App Status |---
App: adc_continuous   -   [Fault]
 Events Queued: 0   Syscall Count: 0   Last Syscall: None

 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x2000C000═╪══════════════════════════════════════════╝
             │ ▼ Grant         268 |   1024          
  0x2000BEF4 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ Unused
  0x20008E20 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ ▲ Heap            0 |   1024              S
  0x20008E20 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ R
             │ Data          17952 |  17952              A
  0x20004800 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ M
             │ ▼ Stack         120 |   2048          
  0x20004788 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ Unused
  0x20004000 ┴───────────────────────────────────────────
             .....
  0x00032000 ┬───────────────────────────────────────────
             │ Unused
  0x00031A11 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ F
             │ Data            298                       L
  0x000318E7 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ A
             │ Text           6259                       S
  0x00030074 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ H
             │ Header          116
  0x00030000 ┴───────────────────────────────────────────

  R0 : 0x200048B4    R6 : 0x200048B4
  R1 : 0x00000010    R7 : 0x20004800
  R2 : 0x20008E10    R8 : 0x000317B7
  R3 : 0x000000A4    R10: 0x00000000
  R4 : 0x00000000    R11: 0x00000000
  R5 : 0x00000018    R12: 0x00000000
  R9 : 0x20004800 (Static Base Register)
  SP : 0x20004788 (Process Stack Pointer)
  LR : 0x00030537 [0x800004C2 in lst file]
  PC : 0x0003053A [0x800004C6 in lst file]
 YPC : 0x00030075 [0x8002E802 in lst file]

 APSR: N 0 Z 0 C 0 V 0 Q 0
       GE 0 0 0 0
 IPSR: Exception Type - Thread Mode
 EPSR: ICI.IT 0x00
       ThumbBit true 
```

### PR DESCRIPTION
**Pull request by alevy**
E.g. for text sections, data sections, grants and ipc regions.
Unfortunately, this currently makes the MPU hil a bit more Cortex-M MPU
specific... working on it.

This is somewhat in progress, but I think it might be worth merging meanwhile.

At this point, it make sense to makes the `Region` type to an associated of the `MPU` trait so it can be implementation specific and cache `Regions` between calls so the calculation is required each time (should drastically reduce the context switch time). However, both of these introduce to typing issues that call for some non-trivial refactoring of the kernel crate, and I'm still experimenting with.

Fixes #382

### CODE REVIEW

File: kernel/src/process.rs [hunk 1]
```diff
@@ -340,96 +340,64 @@ impl<'a> Process<'a> {
...
+                                 mpu::ExecutePermission::ExecutionNotPermitted,
+                                 mpu::AccessPermission::PrivilegedOnly) {
+            None =>
+                panic!("Infeasible MPU allocation. Base {:#x}, Length: {:#x}",
+                           grant_base as usize, grant_len),
+            Some(region) => mpu.set_mpu(region)
+        }
 
         // Setup IPC MPU regions
         for (i, region) in self.mpu_regions.iter().enumerate() {
```
Comment (brghena) [inline kernel/src/process.rs]: You should limit this to a maximum of 5 additional regions (i.e. `iter().enumerate().take(5)`)

File: arch/cortex-m4/src/mpu.rs [hunk 2]
```diff
@@ -116,23 +118,55 @@ impl kernel::mpu::MPU for MPU {
...
     }
 
-    fn set_mpu(&self,
-               region_num: u32,
-               start_addr: u32,
-               len: PowerOfTwo,
-               subregion_mask: u8,
-               execute: kernel::mpu::ExecutePermission,
-               access: kernel::mpu::AccessPermission) {
+    fn create_region(region_num: usize,
```
Comment (brghena) [inline arch/cortex-m4/src/mpu.rs]: Doing checking on region_num and returning `None` if it is greater than 8 would be good.

File: kernel/src/process.rs (hunk 1 above)
Comment (alevy) [inline kernel/src/process.rs]: ah. the `mpu_regions` slice is fixed-legth (to 5), but you're still right

File: arch/cortex-m4/src/mpu.rs [hunk 3]
```diff
@@ -116,23 +118,55 @@ impl kernel::mpu::MPU for MPU {
...
+            let ap = access as u32;
+            Some(unsafe {
+                Region::new((region_start | 1 << 4 | (region_num & 0xf)) as u32,
+                            1 | subregion_mask << 8 | (region_len.exp::<u32>() - 1) << 1 |
+                            ap << 24 | xn << 28)
+            })
+
+        } else {
+            // Text length aligned to text start
+            let region_len = PowerOfTwo::floor(len as u32);
```
Comment (alevy) [inline arch/cortex-m4/src/mpu.rs]: It's more dangerous to use ceiling, I think. You _may_ end up with too small a region if you passed in a non-power-of-two number, but `ceiling` might end up exposing memory from another process, which is worse (i think)

Comment (brghena) [inline arch/cortex-m4/src/mpu.rs]: Hmmm, I see. So this really needs to be handled in concert with the process deciding how big its memory space is, which should use `PowerOfTwo::ceiling` right?

Comment (alevy) [inline arch/cortex-m4/src/mpu.rs]: Yes, precisely

File: arch/cortex-m4/src/mpu.rs [hunk 4]
```diff
@@ -116,23 +118,55 @@ impl kernel::mpu::MPU for MPU {
...
+            let xn = execute as u32;
+            let ap = access as u32;
+            Some(unsafe {
+                Region::new((start | 1 << 4 | (region_num & 0xf)) as u32,
+                            1 | (region_len.exp::<u32>() - 1) << 1 | ap << 24 | xn << 28)
```
Comment (ppannuto) [inline arch/cortex-m4/src/mpu.rs]: I was going to comment on the above `Region::new` that I felt like the region constructor function shouldn't be a simple `u32` of attributes, but Branden explained that the goal is for Region to be chip-agnostic.

In that case, I think it'd be valuable for this file to have a `fn new_region` or some such that breaks down all of the attributes into pieces. That way, you only have the bitshift logic in one place (thus far it's in at least two places) and also lets you consolidate the checks Branden suggested

File: kernel/src/platform/mpu.rs [hunk 5]
```diff
@@ -20,14 +18,41 @@ pub enum ExecutePermission {
     ExecutionNotPermitted = 0b1,
 }
 
+pub struct Region {
```
Comment (ppannuto) [inline kernel/src/platform/mpu.rs]: As this is generic, should it have a `valid` bit or something here? Currently this is working out because bit 0 of attributes is the valid bit and writing the register works, but that's a bit of happenstance. Feels like it might make sense for the "generic" Region struct to have an internal sense of whether it's valid?

Actually, no, I take that back. Anywhere where we'd want an "invalid" region, it should probably just be `None` instead. The _real_ question then is why the `empty` constructor needs to exist? Feels like things should just be putting `None` in wherever `empty` is currently being used (it's a bit of a chip-specific assumption that 0's are a valid "empty" case anyway)

**Comment by alevy** [comment]
@ppannuto I hear your concerns above. I think some of this is alleviated by the bigger refactor I'm working on now which would make `Region` an associated type of the `MPU` trait, so it's entire structure is implementation specific (and likely doesn't have any constructors exposed actually, maybe just an `invalid`/`empty` one). There are some artifacts of that aspriational design reflected here. I _kind of_ don't want to fix those yet because I want to make it easier for me to do the larger refactor (which I believe would result in an overall cleaner design), but will do you if you insist just one more time ;)

File: kernel/src/platform/mpu.rs (hunk 5 above)
Comment (alevy) [inline kernel/src/platform/mpu.rs]: The `empty` constructor is important because even when a region is marked "invalid" we still need to know the region number. This is not _merely_ a choice of who's responsible for the keeping track of the region number because regions can (and do) overlap, and their ordering makes a difference to who "wins".

**Comment by ppannuto** [comment]
Sounds good -- I'm willing to wait :)

File: kernel/src/process.rs (hunk 1 above)
Comment (alevy) [inline kernel/src/process.rs]: Actually, isn't this resolved by returning `None` from `create_region` if the region number is too high, and would be more general not to hard code the number of possible regions here as well?

**Comment by alevy** [comment]
Comments addressed, I think.

File: kernel/src/process.rs (hunk 1 above)
Comment (ppannuto) [inline kernel/src/process.rs]: Yes.. with the caveat that `None` should probably `panic!` here in the interest of failing quickly for the unexpected case (by unexpected, I mean that IPC doesn't work when it's expected to. I think that the request to create a 6th (or N+1th) IPC should've failed gracefully before reaching this code path, which motivates panic'ing here)
