### PR TITLE
userland: make sure stack starts at multiple of 8

### LINKED ISSUE #856: Apps crash when STACK_SIZE not a power of 2
It seems that since the move of crt0.c into libtock specifying a stack size that is not a power of 2 will cause the app to crash. This might be fine, but it would be helpful to at least throw a compile time error for invalid STACK_SIZE if that's the case. The cause of the issue is not obvious from the runtime error (a data access violation, pasted below). 

Note that STACK_SIZE was set to 8182 and APP_HEAP_SIZE was set to 4096 in this example.

```
Running radio_module Version 0.1.0 from git v0.2-530-g6bb7e9e
Kernel panic at /home/adkins/Research/signpost-software/signpost/kernel/tock/kernel/src/process.rs:752:
	"Process radio_app had a fault"

---| Fault Status |---
Data Access Violation:              true
Precise Data Bus Error:             true
Forced Hard Fault:                  true
Faulting Memory Address:            0x868A2000
Bus Fault Address:                  0x868A2000
Fault Status Register (CFSR):       0x00008282
Hard Fault Status Register (HFSR):  0x40000000

---| App Status |---
App: radio_app   -   [Fault]
 Events Queued: 0   Syscall Count: 3   Last Syscall: MEMOP

 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x2000E000═╪══════════════════════════════════════════╝
             │ ▼ Grant         272 |    272          
  0x2000DEF0 ┼───────────────────────────────────────────
             │ Unused
  0x2000AB5A ┼───────────────────────────────────────────
             │ ▲ Heap            0 |  13206               S
  0x2000AB5A ┼─────────────────────────────────────────── R
             │ Data          11108 |  11108               A
  0x20007FF6 ┼─────────────────────────────────────────── M
             │ ▼ Stack          86 |   8182          
  0x20007FA0 ┼───────────────────────────────────────────
             │ Unused
  0x20006000 ┴───────────────────────────────────────────
             .....
  0x00040000 ┬─────────────────────────────────────────── F
             │ App Flash     65488                        L
  0x00030030 ┼─────────────────────────────────────────── A
             │ Protected        48                        S
  0x00030000 ┴─────────────────────────────────────────── H

  R0 : 0x76BA0003    R6 : 0x2000AB5A
  R1 : 0x76BA0003    R7 : 0x00000000
  R2 : 0x20007FF4    R8 : 0x00000000
  R3 : 0x868A2000    R10: 0x00000000
  R4 : 0x00030030    R11: 0x00000000
  R5 : 0x20007FF6    R12: 0x00034F56
  R9 : 0x20007FF4 (Static Base Register)
  SP : 0x20007FA0 (Process Stack Pointer)
  LR : 0x0003081F
  PC : 0x0003534C
 YPC : 0x00030055

 APSR: N 0 Z 0 C 1 V 0 Q 0
       GE 0 0 0 0
 IPSR: Exception Type - Thread Mode
 EPSR: ICI.IT 0x00
       ThumbBit true 
 To debug, run `make debug RAM_START=0x20006000 FLASH_INIT=0x30055`
 in the app's folder and open the .lst file.
```

### PR DESCRIPTION
**Pull request by bradjc**
fixes #856

### Pull Request Overview

This pull request makes sure that c apps put their stack at a multiple of 32 by moving the start of the stack down until that is true.

### Testing Strategy

This pull request was tested by running blink on hail with `STACK_SIZE=8182` in the makefile.

### TODO or Help Wanted

Is this the right solution?

### Documentation Updated

- [x] Kernel: Updated the relevant files in `/docs`, or no updates are required.
- [x] Userland: Added/updated the application README, if needed.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
Where does 32 come from? I thought AAPCS only required 8-byte alignment for the stack

Is it a MPU limitation? I think that's subtler, as the minimum alignment is limited by the subregion size, which is limited by the total region size.

**Comment by bradjc** [comment]
Well 32 is a multiple of 8! No, it actually seems like it has to be a multiple of 4. `8180` and `8184` work, `8182` does not.

I now realize that I need to do a `make clean` first for my tests to be valid...

File: userland/libtock/crt0.c [hunk 1]
```diff
@@ -47,8 +47,9 @@ void _start(void* text_start,
             void* app_heap_break __attribute__((unused))) {
 
   // Allocate stack and data. `brk` to STACK_SIZE + got_size + data_size +
-  // bss_size from start of memory
-  uint32_t stacktop = (uint32_t)mem_start + STACK_SIZE;
+  // bss_size from start of memory. The stack must be aligned to a multiple of
+  // 4 so enforce that here.
```
Comment (ppannuto) [inline userland/libtock/crt0.c]: § 5.2.1.2 requires that at a "public interface", the stack be 8-byte aligned. I think the initial stack location probably qualifies as "public" (though I'm not surprised the 4-byte works in practice, we should probably stick 8 on general principles)
http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042f/IHI0042F_aapcs.pdf

I think it'd also be good to update this comment to indicate where the alignment requirement comes from

File: userland/libtock/crt0.c [hunk 2]
```diff
@@ -47,8 +47,9 @@ void _start(void* text_start,
...
+  uint32_t stacktop = (uint32_t)mem_start + (STACK_SIZE & 0xFFFFFFFC);
```
Comment (ppannuto) [inline userland/libtock/crt0.c]: Does this method possibly shrink the requested STACK_SIZE by up to 4 (or soon 8) bytes? Feels like we should err on being too large rather than too small.

Comment (ppannuto) [reply userland/libtock/crt0.c]: Also, I don't think we have any guarantees on the alignment of mem_start here? Should this thus be something like `(mem_start + STACK_SIZE + 0x7) % 0xFFFF_FFF8` ?

**Comment by bradjc** [comment]
Attempt #2!
